[package]
name = "xny-cli"
edition = "2021"
version = "1.0.0"

[dependencies]
serde_json = "1.0.94"
url = "2.3.1"
clap = { version = "4.2.1", features = ["derive"] }

[dependencies.minreq]
version = "2.7.0"
features = ["https-rustls"]
optional = false
default-features = false

[dependencies.serde]
version = "1.0"
features = ["serde_derive"]
optional = false
default-features = false

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

